spring:
  profiles:
    active: prod

destinations:
  queues:
    test:
      exchange: test
      routing-key: test

log4j:
  category:
    org:
      springframework:
        data:
          mongodb: DEBUG
  appender:
    stdout:
      layout: ConversionPattern=%d{ABSOLUTE} %5p %40.40c:%4L - %m%n